---
# defaults file for ansible/roles/configure-k8s

addr_node_master: "{{ ansible_default_ipv4.address }}"
pod_cidr: "10.20.0.0/16"
url_helm: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
url_weave_net: https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
metallb_ipaddrpool:  >-
          {{
            play_hosts
            | map('extract', hostvars, ['ansible_default_ipv4', 'address'])
            | select('defined')
            | map('regex_replace', '$', '/32')
            | list
          }}