---
- name: Install Python dependencies
  ansible.builtin.pip:
    name:
      - kubernetes
      - PyYAML
      - jsonpatch
    state: present

- name: Download helm
  ansible.builtin.get_url:
    url: "{{ url_helm }}"
    dest: /tmp/get_helm.sh
    mode: 0700
  register: download

- name: Install Helm
  ansible.builtin.shell: /tmp/get_helm.sh
  when:
    - download.failed|bool == false

- name: Add stable chart repo NGINX
  kubernetes.core.helm_repository:
    name: nginx-stable
    repo_url: https://kubernetes.github.io/ingress-nginx
    
- name: Install NGINX Ingress Controller
  kubernetes.core.helm:
    name: nginx-stable
    chart_ref: nginx-stable/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    state: present
    update_repo_cache: true

- name: Add stable chart repo metallb
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: "https://metallb.github.io/metallb"

- name: Install metallb baremetal
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: metallb-system
    create_namespace: true
    state: present
    update_repo_cache: true

- name: Create manifest metallb IPAddressPool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: default
        namespace: metallb-system
      spec:
        addresses: "{{ metallb_ipaddrpool }}"
        autoAssign: true
      
- name: Create manifest metallb L2Advertisement
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: default
        namespace: metallb-system
      spec:
        ipAddressPools:
        - default

